# Generated by Django 6.0.5 on 2026-05-26 01:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('producto', '0002_remove_producto_stock'),
    ]

    operations = [
        migrations.AlterField(
            model_name='producto',
            name='nombre',
            field=models.CharField(max_length=100, unique=True),
        ),
    ]
